services:
  system-manager:
    build: .
    container_name: system-manager
    network_mode: host
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc:/host/etc:ro
      - /run/user:/run/user:ro
      - /var/run/dbus:/var/run/dbus:ro
      - /sys/class/dmi:/sys/class/dmi:ro
    env_file:
      - .env
    environment:
      - HOST_ROOT=/host
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
      - NET_ADMIN
      - CAP_DAC_READ_SEARCH
    restart: unless-stopped